site_name: Python MCP Template
site_author: Your Name
theme:
  name: readthedocs
plugins:
  - search
nav:
  - Home: index.md
  - API Reference:
    - Endpoints: reference/endpoints.md
    - Data Models: reference/models.md
